name: Kang Cloud System

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to start the first run manually

jobs:
  long_running_job:
    runs-on: ghcr.io/cirruslabs/macos-runner:tahoe
    timeout-minutes: 1440

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Keep-Alive Heartbeat
        run: |
          echo "Starting heartbeat..."
          end=$((SECONDS + 86400))
          while [ $SECONDS -lt $end ]; do
            echo "Workflow is still running... $(date)"
            sleep 5
          done

      - name: Run Main Task
        run: |
          echo "Starting main job..."
          sleep 21595
          echo "Main job completed."
